{% set name = "django-bootstrap4" %}
{% set version = "25.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_bootstrap4-{{ version }}.tar.gz
  sha256: 6e05d17dda5922ec643e40bb804c7f399ec262c3723a4e5aef5bd550b3ff4ffa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - django >=4.2
    - beautifulsoup4 >=4.10.0

test:
  source_files:
    - tests
    - manage.py
  imports:
    - bootstrap4
    - bootstrap4.templatetags
  commands:
    - pip check
    - python manage.py test
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/zostera/django-bootstrap4
  summary: Bootstrap 4 for Django
  license: BSD-3-Clause
  license_file: LICENSE
  description:  Write Django as usual, and let django-bootstrap4 make template output into Bootstrap 4 code.
  doc_url: http://django-bootstrap4.readthedocs.io/
  dev_url: https://github.com/zostera/django-bootstrap4

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - maksdan
    - davner
