{% set name = "django-bootstrap4" %}
{% set version = "2.1.1" %}
{% set sha256 = "69a68ecf8d6526c33b4c79b51ac07f3a55d3740c9a126171325133108590fff8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python
    - django >=1.11

test:
  imports:
    - bootstrap4
    - bootstrap4.templatetags

about:
  home: https://github.com/zostera/django-bootstrap4
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Bootstrap 4 integration with Django.
  description: Write Django as usual, and let django-bootstrap4 make template output into Bootstrap 4 code.
  doc_url: http://django-bootstrap4.readthedocs.io/
  dev_url: https://github.com/zostera/django-bootstrap4

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
